version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cxrus
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: